#!/bin/sh
# Regenerates THIRD_PARTY_NOTICES.md: the licences of everything inkpress
# redistributes. Run after changing go.mod or the default template's fonts.
set -eu
cd "$(dirname "$0")/.."

out=THIRD_PARTY_NOTICES.md
modcache=$(go env GOMODCACHE)

# Module paths are stored case-encoded in the module cache: A -> !a.
cachepath() { printf '%s' "$1" | sed 's/[A-Z]/!&/g' | tr 'A-Z' 'a-z'; }

licence() {
  # The first licence-like file in a directory, verbatim.
  f=$(ls "$1" 2>/dev/null | grep -iE '^(licen[cs]e|copying)' | head -1)
  if [ -n "$f" ]; then
    printf '```text\n'
    cat "$1/$f"
    printf '\n```\n'
  else
    printf '_No licence file found in %s._\n' "$1"
  fi
}

{
cat <<'EOF'
# Third-party notices

inkpress itself is licensed under the Apache License 2.0 (see `LICENSE` and
`NOTICE`). It redistributes the software and assets below. This file lists each
with its licence text, as the licences require. It is generated by
`scripts/notices.sh`; do not edit it by hand.

inkpress is not affiliated with or endorsed by IBM. IBM Plex is used only to
name the typeface the default template uses.

## Bundled assets

These files are in the repository and embedded in the inkpress binary.

### IBM Plex Sans

`internal/scaffold/pack/.templates/default/fonts/*.ttf`, unmodified, from
<https://github.com/IBM/plex>. Licensed under the SIL Open Font License 1.1.
`inkpress new` copies them into new packs, and PDFs embed subsets of them,
which the licence permits.

EOF
cat internal/scaffold/pack/.templates/default/fonts/LICENSE.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

## Go modules

These are compiled into the inkpress binary.

EOF
go list -deps -f '{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}}{{end}}{{end}}' ./cmd/inkpress |
  sort -u |
  while read -r path version; do
    printf '### %s %s\n\n' "$path" "$version"
    licence "$modcache/$(cachepath "$path")@$version"
    printf '\n'
  done
} > "$out"

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
